version: '3.8'

services:

db:
  container-name: pg_container
  image: postgres:11-alpine
  environment:
    POSTGRES_DB: base
    POSTGRES_PASSWORD: 123456
    POSTGRES_USER: postgres
  ports:
    - "5432:5432"
  volumes: 
    - pg_data:/var/lib/postgresql/data/

volumes:
  pg_data:
